### ISSUE TITLE
Riak ping proxy call results in 500

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#106]
If you point Explorer at a cluster running Riak version 1.4, it succeeds in getting a list of nodes.
However, when Explorer goes to ping each node (via the `/riak/nodes/$node/ping` proxy endpoint), it results in  the following `500 Internal Server Error`:

```erlang
{error, {badmatch,undefined},
       [{re_riak,http_listener,1,[{file,"src/re_riak.erl"},{line,677}]},
        {re_wm_riak_proxy,service_available,2,
                          [{file,"src/re_wm_riak_proxy.erl"},{line,61}]},
        {webmachine_resource,resource_call,3,
                             [{file,"src/webmachine_resource.erl"},
                              {line,186}]},
        {webmachine_resource,do,3,
                             [{file,"src/webmachine_resource.erl"},
                              {line,142}]},
        {webmachine_decision_core,resource_call,1,
                                  [{file,"src/webmachine_decision_core.erl"},
                                   {line,48}]},
        {webmachine_decision_core,decision,1,
                                  [{file,"src/webmachine_decision_core.erl"},
                                   {line,162}]},
        {webmachine_decision_core,handle_request,2,
                                  [{file,"src/webmachine_decision_core.erl"},
                                   {line,33}]},
        {webmachine_mochiweb,loop,2,
                             [{file,"src/webmachine_mochiweb.erl"},
                              {line,72}]}]}
```

Given that Riak 1.4 is end-of-life'd, this is not urgent. However, it is almost certain that somebody will try to use Explorer with a pre-2.0 cluster, so I was checking to see what happens.
Surprisingly, it was able to get a list of nodes for the cluster.
However, it failed on the riak ping, which I was not expecting.
So, out of curiosity - why is the simple proxy ping failing? (And, is it worth fixing?)

**Comment by dmitrizagidulin** [comment]
Actually, a proxy Riak ping also results in a 500 error even on Riak 2.1, if that node is not running:

```erlang
{error,{badmatch,{badrpc,nodedown}},
       [{re_riak,http_listener,1,[{file,"src/re_riak.erl"},{line,677}]},
        {re_wm_riak_proxy,service_available,2,
                          [{file,"src/re_wm_riak_proxy.erl"},{line,61}]},
        {webmachine_resource,resource_call,3,
                             [{file,"src/webmachine_resource.erl"},
                              {line,186}]},
        {webmachine_resource,do,3,
                             [{file,"src/webmachine_resource.erl"},
                              {line,142}]},
        {webmachine_decision_core,resource_call,1,
                                  [{file,"src/webmachine_decision_core.erl"},
                                   {line,48}]},
        {webmachine_decision_core,decision,1,
                                  [{file,"src/webmachine_decision_core.erl"},
                                   {line,162}]},
        {webmachine_decision_core,handle_request,2,
                                  [{file,"src/webmachine_decision_core.erl"},
                                   {line,33}]},
        {webmachine_mochiweb,loop,2,
                             [{file,"src/webmachine_mochiweb.erl"},
                              {line,72}]}]}
```

So, definitely should be fixed.

**Comment by drewkerrigan** [comment]
Looks like proxy calls are failing because we are trying to get the http listener by doing application:get_env(riak_api, http)

but the old (1.4.*) way was application:get_env(riak_kv, web_ip), application:get_env(riak_kv, web_port).

I could add support for that, but a lot of other stuff on the frontend would likely need to change because of the lack of bucket types in 1.4. In other words, ping would work, but most of the rest of riak explorer would fail due to the assumption that bucket types exist.

As for the other problem: 500 when a node isn't running. That should be easier to fix

**Comment by drewkerrigan** [comment]
The secondary node-isn't-running 500 should be fixed in master now.

**Comment by dmitrizagidulin** [comment]
Ah, ok, support for 1.4 definitely is not a priority. I wanted to ask about the mechanism in case it pointed to something we overlooked. We can put 1.4 ping aside.

**Comment by dmitrizagidulin** [comment]
Tested the 500 error on a 2.0+ riak node when it's not running, works as expected.
