### ISSUE TITLE
Fix `/explore/clusters/$cluster/nodes/$node` endpoint

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#110]
The `/explore/clusters/$cluster/nodes/$node` endpoint is currently broken, just returns a 404.

```
curl localhost:9000/explore/clusters/default/nodes
{
    "links": {
        "self": "/explore/clusters/default/nodes"
    },
    "nodes": [
        {
            "id": "riak@127.0.0.1"
        }
    ]
}
```

but

```
curl localhost:9000/explore/clusters/default/nodes/riak@127.0.0.1
404 Not Found
```

The `/config` endpoint for that node works, though:

```
curl localhost:9000/explore/clusters/default/nodes/riak@127.0.0.1/config
200 OK, long effective config json
```

**Comment by travisbhartwell** [comment]
I wonder if what I added for the config endpoint broke this.  I'll look into it.

Definite motivation for the integration tests I've started working on today. :)

**Comment by dmitrizagidulin** [comment]
Hahaha, yea, I was just thinking that, re integration tests :)
