### ISSUE TITLE
Riak Patch Version Download Access Denied (Ubuntu)

### ISSUE THREAD

**Issue by dklesev** [basho-labs/riak_explorer#115]
When trying to download patch version http://riak-tools.s3.amazonaws.com/riak_explorer_addon_linux_amd64.tar.gz access is denied.

**Comment by drewkerrigan** [comment]
whoops, let me fix that.

**Comment by drewkerrigan** [comment]
@dklesev ok, should be up now. The addon version is just 2.2MB.
