### ISSUE TITLE
Allow sorting capability for cached bucket and key lists (by alpha)

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#118]
Add an optional `?sort=true` parameter (defaults to true) to the two cache refresh endpoints:

```
curl -XPOST \
  /explore/clusters/$cluster/bucket_types/$type/refresh_buckets/source/riak_kv?sort=true

curl -XPOST \
  /explore/clusters/$cluster/bucket_types/$type/buckets/$bucket/refresh_keys/source/riak_kv?sort=true
```

When set to true, the cached key lists or bucket lists (that are stored as flat text files on the API-side) will be sorted alphabetically.

This will dramatically improve the user experience (when in dev mode), alongside the existing pagination functionality.

**Comment by drewkerrigan** [comment]
Done

**Comment by dmitrizagidulin** [comment]
Wow, nicely done. While we're on the subject of sorting, any chance we can also sort the other 3 lists, server-side?

* clusters
* bucket types
* nodes

**Comment by drewkerrigan** [comment]
yeah I can do that fairly easily I think

**Comment by drewkerrigan** [comment]
done with sorting clusters/bucket types / nodes

**Comment by dmitrizagidulin** [comment]
Tested, works great for all the resources mentioned (keys, buckets, bucket types, clusters, nodes). Thanks Drew! Closing.
