### ISSUE TITLE
Can't use nginx reverse proxy in front of riak_explorer

### ISSUE THREAD

**Issue by mattrochon** [basho-labs/riak_explorer#133]
So I use an nginx reverse proxy to secure and monitor access to all of our dev and production toolsets.

This works for literally everything I have ever used it for except riak_explorer. I have included my current configs for it, as well as a description of the behaviour i am seeing, vs what I expect at the bottom.

RIAK_EXPLORER index,html

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Riak Explorer</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <base href="explorer/" />
<meta name="ember-riak-explorer/config/environment" content="%7B%20%22modulePrefix%22%3A%20%22ember-riak-explorer%22%2C%20%22podModulePrefix%22%3A%20%22ember-riak-explorer%2Fpods%22%2C%20%22environment%22%3A%20%22development%22%2C%20%22baseURL%22%3A%20%22%2Fexplorer%2F%22%2C%20%22locationType%22%3A%20%22auto%22%2C%20%22EmberENV%22%3A%20%7B%20%22FEATURES%22%3A%20%7B%7D%20%7D%2C%20%22APP%22%3A%20%7B%20%22name%22%3A%20%22ember-riak-explorer%22%2C%20%22version%22%3A%20%220.0.0%20053bcaaa%22%20%7D%2C%20%22contentSecurityPolicy%22%3A%20%7B%20%22default-src%22%3A%20%22%27none%27%22%2C%20%22script-src%22%3A%20%22%27self%27%20%27unsafe-inline%27%20%27unsafe-eval%27%22%2C%20%22connect-src%22%3A%20%22%27self%27%22%2C%20%22img-src%22%3A%20%22%27self%27%22%2C%20%22style-src%22%3A%20%22%27self%27%20%27unsafe-inline%27%22%2C%20%22font-src%22%3A%20%22%27self%27%22%2C%20%22media-src%22%3A%20%22%27self%27%22%20%7D%2C%20%22contentSecurityPolicyHeader%22%3A%20%22Content-Security-Policy-Report-Only%22%2C%20%22exportApplicationGlobal%22%3A%20true%20%7D" />
    <link rel="stylesheet" href="assets/ember-riak-explorer.css">

  </head>
  <body>

    <script src="assets/vendor.js"></script>
    <script src="assets/ember-riak-explorer.js"></script>

  </body>
</html>
```

For ease of reading, the embedded urlencoded environment file:

``` json
{
    "modulePrefix": "ember-riak-explorer",
    "podModulePrefix": "ember-riak-explorer/pods",
    "environment": "development",
    "baseURL": "/explorer/",
    "locationType": "auto",
    "EmberENV": {
        "FEATURES": {}
    },
    "APP": {
        "name": "ember-riak-explorer",
        "version": "0.0.0 053bcaaa"
    },
    "contentSecurityPolicy": {
        "default-src": "'none'",
        "script-src": "'self' 'unsafe-inline' 'unsafe-eval'",
        "connect-src": "'self'",
        "img-src": "'self'",
        "style-src": "'self' 'unsafe-inline'",
        "font-src": "'self'",
        "media-src": "'self'"
    },
    "contentSecurityPolicyHeader": "Content-Security-Policy-Report-Only",
    "exportApplicationGlobal": true
}
```

The nginx proxy location:

```
location /explorer {

        auth_pam "secured";
        auth_pam_service_name "nginx";

        proxy_buffering off;
        proxy_redirect off;
        proxy_read_timeout 1500;
        proxy_send_timeout 1500;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Original-URI $request_uri;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://riak-explorer:9000/explorer;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }
```

I use this standard configuration for many services but with explorer I get the following behaviour:

1) Requests to any url inside the reverse proxy are always returning the riak_explorer index.html file.

When i would expect the following:

1) Requests serve the file path they are requesting

I know I am doing something wrong but I have lost 2 days on this already and am hoping someone can help point me int he right direction.

**Comment by randysecrist** [comment]
I haven't yet set up a nginx reverse proxy with explorer, but I have used nginx many times in my life.  I can't see a reason why any reverse proxy wouldn't work with explorer.  If I get some time later, I may spin up an environment and put together a sample config.

On the surface tho, I suspect there is something wrong with how you are using the location + proxy_pass directive of nginx.

**Comment by mattrochon** [comment]
Well the strange part is i have been using this nginx config for years on many different services and it works correctly. With both riak explorer and riak control though, I get this issue. I suspect it is related to a difference int he way erlang servers are mapping paths for ui resources. Though admittedly my experience with erlang is as a user and not a developer so I really might be wrong.

**Comment by randysecrist** [comment]
What does the connection between explorer and riak look like?  Is HTTP and PBC open?  Can explorer connect to riak via disterl?

**Comment by randysecrist** [comment]
closing this as a non issue; have not been able to reproduce
