### ISSUE TITLE
CentOS

### ISSUE THREAD

**Issue by jrphilli** [basho-labs/riak_explorer#141]
Please provide packages for CentOS.  I would like to install Riak Explorer on CentOS 7 from a package.

**Comment by drewkerrigan** [comment]
@jrphilli There should be CentOS packages now available, please test them out! https://github.com/basho-labs/riak_explorer/releases/tag/1.0.0

**Comment by jrphilli** [comment]
Thanks!  I used the CentOS packages on a couple of our clusters and did not encounter any issues.  My team is going to be thrilled!

**Comment by drewkerrigan** [comment]
Great, closing this issue now
