### ISSUE TITLE
Implement 'Edit Counter' view

### ISSUE THREAD

**Issue by dmitrizagidulin** [basho-labs/riak_explorer#45]
Add the ability to edit / reset a CRDT Counter type object.

**Comment by cmeiklejohn** [comment]
Just to be clear, counters are not "edited."  They are "incremented" or "decremented", depending on the variant of counter you are working with.  "Editing" the counter could result in the counters failing to converge deterministically.

**Comment by dmitrizagidulin** [comment]
@cmeiklejohn no worries, the actual implemented Counter screen just exposes increment / decrement.
