### ISSUE TITLE
Fix ajax calls (and other urls) to allow for a custom base URI

### ISSUE THREAD

**Issue by drewkerrigan** [basho-labs/riak_explorer#78]
Currently there are lots of hard coded absolute URI's throughout the code such as "/explore/..."

It would be nice if those modules included the config/environment.js and made use of the baseURL config option so that the UI can be used in more varied environments.

**Comment by dmitrizagidulin** [comment]
Jira ticket # REX-83

**Comment by dmitrizagidulin** [comment]
There's two things to consider.

One is the `baseURL` variable in `config/environment.js`. This controls where Ember expects static files to live (the CSS and .js files).

The other one is the prefix for the API (for the `/explore`, `/control` and `/riak` endpoints). Is it safe to assume that we can just use the same setting for both of them?

**Comment by drewkerrigan** [comment]
Yes, the baseURL should be the root for all static assets, and also the starting path for any of the other API routes (/explore, /control, /riak, etc).

**Comment by dmitrizagidulin** [comment]
Ok, fixed in the most recent commits. The Explorer service (in `services/explorer.js`), the Store adapter (in `adapters/explorer-resource.js`) and the handful of hardcoded URLs (which will be cleaned up in due course) all use the `baseURL` variable from `config/environment.js`
