### ISSUE TITLE
crash on crypto:hash

### ISSUE THREAD

**Issue by eshubin** [basho-labs/riak_explorer#79]
I tried to  use a binary for ubuntu and got the following error:
Internal Server Error

The server encountered an error while processing this request:
[{webmachine_util,escape_quotes,
     [{error,
          {error,undef,
              [{crypto,hash,
                   [sha,
                    <<"\n\n  \n    \n    \n    \n    \n    \n\n    \n\n\n    \n    \n    \n\n    \n  \n  \n\n\n\n    \n    \n\n    \n  \n\n">>],
                   []},
               {re_wm_static,hash_body,1,
                   [{file,"src/re_wm_static.erl"},{line,114}]},
               {re_wm_static,generate_etag,2,
                   [{file,"src/re_wm_static.erl"},{line,87}]},
               {webmachine_resource,resource_call,3,
                   [{file,"src/webmachine_resource.erl"},{line,186}]},
               {webmachine_resource,do,3,
                   [{file,"src/webmachine_resource.erl"},{line,142}]},
               {webmachine_decision_core,resource_call,1,
                   [{file,"src/webmachine_decision_core.erl"},{line,48}]},
               {webmachine_decision_core,decision,1,
                   [{file,"src/webmachine_decision_core.erl"},{line,543}]},
               {webmachine_decision_core,handle_request,2,
                   [{file,"src/webmachine_decision_core.erl"},{line,33}]}]}},
      "\""],
     [{file,"src/webmachine_util.erl"},{line,342}]},
 {webmachine_decision_core,decision,1,
     [{file,"src/webmachine_decision_core.erl"},{line,545}]},
 {webmachine_decision_core,handle_request,2,
     [{file,"src/webmachine_decision_core.erl"},{line,33}]},
 {webmachine_mochiweb,loop,2,[{file,"src/webmachine_mochiweb.erl"},{line,72}]},
 {mochiweb_http,headers,5,[{file,"src/mochiweb_http.erl"},{line,96}]},
 {proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,239}]}]
mochiweb+webmachine web server

**Comment by kri5** [comment]
Same here, any ideas?

**Comment by drewkerrigan** [comment]
Hello @eshubin @kri5, The downloadable binaries are likely out of date, but the `{error,undef [{crypto,hash` error points to issues with open ssl not being installed either on the system that it was built on, or the system it's running on. Your best bet at getting it running until we upload new binaries would be to compile it now from source by first installing erlang with crypto enabled [http://docs.basho.com/riak/latest/ops/building/installing/erlang/](http://docs.basho.com/riak/latest/ops/building/installing/erlang/) and then running `make rel`. That should give you the `rel/riak_explorer` directory with the executable at `rel/riak_explorer/bin/riak_explorer`.

**Comment by drewkerrigan** [comment]
@eshubin @kri5 I just uploaded new builds, could you try again to see if you're still getting the crypto issues?

http://riak-tools.s3.amazonaws.com/riak_explorer_darwin_amd64.tar.gz for mac or
http://riak-tools.s3.amazonaws.com/riak_explorer_linux_amd64.tar.gz for ubuntu (14.04)

**Comment by eshubin** [comment]
New one works, thanks
